# Generated by Django 5.1.1 on 2024-10-23 16:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnimeVariety",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="animeimg/")),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "types",
                    models.CharField(
                        choices=[
                            ("JK", "JUJUTSUKAISEN"),
                            ("NR", "NARUTO"),
                            ("AO", "ATTACKONTITAN"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
        ),
    ]
