# Generated by Django 5.1.1 on 2024-10-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schulen", "0003_animevariety_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animevariety",
            name="types",
            field=models.CharField(
                choices=[
                    ("LS", "LONGSEASONS"),
                    ("MP", "MASTERPIECE"),
                    ("AT", "ACTIONTHRILLER"),
                ],
                max_length=2,
            ),
        ),
    ]
