# Generated by Django 5.1.1 on 2024-10-27 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schulen", "0005_animecertificate_animereview_store"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animereview",
            name="rating",
            field=models.IntegerField(default=""),
        ),
        migrations.CreateModel(
            name="AnimeUA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age_certification", models.IntegerField()),
                (
                    "ua_rating",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schulen.animevariety",
                    ),
                ),
            ],
        ),
    ]
