# Generated by Django 5.1.1 on 2024-10-27 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schulen", "0006_alter_animereview_rating_animeua"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animeua",
            name="ua_rating",
        ),
        migrations.AddField(
            model_name="animeua",
            name="animeua",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ua_rating",
                to="schulen.animevariety",
            ),
        ),
        migrations.AlterField(
            model_name="animeua",
            name="age_certification",
            field=models.IntegerField(default=""),
        ),
    ]
